# Generated by Django 3.2.12 on 2022-08-25 12:04

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servable',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('text/css', 'CSS'), ('text/csv', 'CSV'), ('text/html', 'HTML'), ('text/plain', 'Plain Text'), ('text/xml', 'XML (text/xml)'), ('application/javascript', 'JavaScript'), ('application/xml', 'XML (application/XML)'), ('application/json', 'JSON')], max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
