# Generated by Django 3.2.12 on 2022-03-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='destination',
            field=models.URLField(),
        ),
    ]
