# Generated by Django 3.2.12 on 2022-06-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0003_visit_squashed_0005_visit_http_response_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='requested_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='redirect.reference'),
        ),
    ]
